name: cola_framework
description: A Flutter application framework that provides commonly used packages which depend on `go_router` and `riverpod`
version: 0.0.1
homepage: https://github.com/khwgit/cola_framework
publish_to: "none"

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  go_router: ^14.0.0
  hooks_riverpod: ^2.5.0
  meta: any
  logging: ^1.2.0
  stack_trace: ^1.11.0

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
